[phases.setup]
nixPkgs = ["python311", "cmake", "gcc"]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install --prefer-binary --no-pre --timeout=600 -r requirements.txt"
]

[start]
cmd = "python app.py"

